"""
Clinic data extracted from Familiar Clinic Names_20260130.xlsx.

Each entry maps a PZ code + region to a familiar clinic name.
Many PZ codes have multiple familiar names (same diabetes unit,
different clinic sites).
"""

CLINICS = [
    {"pz_code": "PZ001", "region": "Wales", "name": "Morriston Paediatric Diabetes clinic"},
    {"pz_code": "PZ002", "region": "East of England", "name": "Norfolk and Norwich University Hospital"},
    {"pz_code": "PZ004", "region": "East Midlands", "name": "Northampton General Hospital - Children and Young Persons' Diabetes Clinic"},
    {"pz_code": "PZ005", "region": "East Midlands", "name": "Derbyshire Children's Hospital"},
    {"pz_code": "PZ006", "region": "Yorkshire & Humber", "name": "Doncaster Royal Infirmary"},
    {"pz_code": "PZ007", "region": "Thames Valley", "name": "Oxford Children's Diabetes Service"},
    {"pz_code": "PZ009", "region": "North West", "name": "Macclesfield Paediatric Diabetes Clinic"},
    {"pz_code": "PZ010", "region": "East of England", "name": "Luton and Dunstable Hospital"},
    {"pz_code": "PZ011", "region": "Wales", "name": "Glan Clwyd Hospital Children's Diabetes Clinic"},
    {"pz_code": "PZ012", "region": "London & South East", "name": "Barnet General Hospital - Paediatric Diabetes Clinic"},
    {"pz_code": "PZ014", "region": "London & South East", "name": "Chase Farm Hospital - Paediatric Diabetes Clinic"},
    {"pz_code": "PZ015", "region": "North West", "name": "Wythenshawe Hospital"},
    {"pz_code": "PZ016", "region": "Yorkshire & Humber", "name": "Bassetlaw District General Hospital - Young Person's Clinic & Diabetic Paediatric Clinic"},
    {"pz_code": "PZ017", "region": "South Central", "name": "Dorset County Hospital"},
    {"pz_code": "PZ018", "region": "South Central", "name": "Worthing Hospital"},
    {"pz_code": "PZ019", "region": "East of England", "name": "Basildon Hospital"},
    {"pz_code": "PZ020", "region": "Yorkshire & Humber", "name": "Diana, Princess of Wales Hospital"},
    {"pz_code": "PZ021", "region": "Thames Valley", "name": "Wexham Park Hospital"},
    {"pz_code": "PZ022", "region": "North East & North Cumbria", "name": "West Cumberland Hospital (Whitehaven)"},
    {"pz_code": "PZ022", "region": "North East & North Cumbria", "name": "Workington Community Hospital"},
    {"pz_code": "PZ023", "region": "London & South East", "name": "St George's Hospital"},
    {"pz_code": "PZ024", "region": "London & South East", "name": "East Kent Children's Diabetes Team"},
    {"pz_code": "PZ026", "region": "Yorkshire & Humber", "name": "Hull Royal Infirmary - Paediatric/Transition Diabetes Clinic"},
    {"pz_code": "PZ028", "region": "Thames Valley", "name": "Stoke Mandeville Hospital"},
    {"pz_code": "PZ030", "region": "North West", "name": "Leighton Hospital"},
    {"pz_code": "PZ031", "region": "South Central", "name": "St Richard's Hospital"},
    {"pz_code": "PZ032", "region": "North East & North Cumbria", "name": "Great North Children's Hospital - Newcastle Children and Young People's Diabetes Team"},
    {"pz_code": "PZ033", "region": "East Midlands", "name": "Queens Hospital Burton-on-Trent"},
    {"pz_code": "PZ034", "region": "South Central", "name": "Royal Hampshire County Hospital"},
    {"pz_code": "PZ035", "region": "Thames Valley", "name": "Royal Berkshire Hospital - Paediatric Diabetes Unit"},
    {"pz_code": "PZ036", "region": "London & South East", "name": "Whipps Cross University Hospital"},
    {"pz_code": "PZ038", "region": "Thames Valley", "name": "Wycombe General Hospital"},
    {"pz_code": "PZ040", "region": "West Midlands", "name": "Heartlands Hospital Diabetes Clinic"},
    {"pz_code": "PZ041", "region": "East of England", "name": "Addenbrooke's Hospital"},
    {"pz_code": "PZ042", "region": "East Midlands", "name": "Nottingham Children's Hospital Paediatric Diabetes Unit"},
    {"pz_code": "PZ045", "region": "London & South East", "name": "Whittington Diabetes Team"},
    {"pz_code": "PZ047", "region": "Yorkshire & Humber", "name": "Airedale Paediatric Diabetes Unit"},
    {"pz_code": "PZ048", "region": "East Midlands", "name": "Lincoln County Hospital"},
    {"pz_code": "PZ049", "region": "North West", "name": "Halton Paediatric Diabetes Clinic"},
    {"pz_code": "PZ049", "region": "North West", "name": "Warrington Paediatric Diabetes Clinic"},
    {"pz_code": "PZ050", "region": "London & South East", "name": "Epsom General Hospital"},
    {"pz_code": "PZ050", "region": "London & South East", "name": "Queen Mary's Hospital for Children (St Helier Hospital)"},
    {"pz_code": "PZ053", "region": "Yorkshire & Humber", "name": "Scunthorpe General Hospital"},
    {"pz_code": "PZ054", "region": "South Central", "name": "University Hospitals Dorset"},
    {"pz_code": "PZ055", "region": "East Midlands", "name": "Leicester Royal Infirmary"},
    {"pz_code": "PZ057", "region": "London & South East", "name": "Kingston Hospital - Paediatric Diabetes Unit"},
    {"pz_code": "PZ058", "region": "London & South East", "name": "Newham University Hospital"},
    {"pz_code": "PZ059", "region": "London & South East", "name": "Royal London Hospital"},
    {"pz_code": "PZ060", "region": "South West", "name": "Royal Devon and Exeter Hospital - Children and Young People's Diabetes Service"},
    {"pz_code": "PZ062", "region": "London & South East", "name": "Croydon University Hospital"},
    {"pz_code": "PZ064", "region": "East Midlands", "name": "Chesterfield Royal Hospital - Paediatric Diabetes Team"},
    {"pz_code": "PZ065", "region": "West Midlands", "name": "County Hospital"},
    {"pz_code": "PZ067", "region": "South West", "name": "Royal Cornwall Hospital"},
    {"pz_code": "PZ068", "region": "South West", "name": "Royal United Hospital"},
    {"pz_code": "PZ069", "region": "North West", "name": "Stepping Hill Hospital - Stockport Children & Young People's Diabetes Team"},
    {"pz_code": "PZ072", "region": "East of England", "name": "West Suffolk Paediatric Diabetes Clinic"},
    {"pz_code": "PZ073", "region": "West Midlands", "name": "Alexandra Hospital (Redditch)"},
    {"pz_code": "PZ074", "region": "North West", "name": "Alder Hey NHS Foundation Trust"},
    {"pz_code": "PZ075", "region": "South Central", "name": "St Mary's Hospital (Isle of Wight)"},
    {"pz_code": "PZ076", "region": "East of England", "name": "Colchester General Hospital"},
    {"pz_code": "PZ078", "region": "West Midlands", "name": "Royal Stoke University Hospital"},
    {"pz_code": "PZ082", "region": "London & South East", "name": "Evelina London Children's Hospital - Paediatric Diabetes Department"},
    {"pz_code": "PZ084", "region": "West Midlands", "name": "Kidderminster Hospital"},
    {"pz_code": "PZ085", "region": "London & South East", "name": "Princess Royal Hospital - Paediatric Diabetes Team"},
    {"pz_code": "PZ086", "region": "East of England", "name": "Hinchingbrooke Hospital"},
    {"pz_code": "PZ088", "region": "London & South East", "name": "Royal Surrey County Hospital - Paediatric Diabetes Clinic/ Cedar Centre"},
    {"pz_code": "PZ089", "region": "London & South East", "name": "Northwick Park Hospital Children's Diabetes Clinic"},
    {"pz_code": "PZ091", "region": "North West", "name": "Burnley General Hospital"},
    {"pz_code": "PZ091", "region": "North West", "name": "Rossendale Primary Health Care Centre"},
    {"pz_code": "PZ091", "region": "North West", "name": "Royal Blackburn Hospital"},
    {"pz_code": "PZ092", "region": "Wales", "name": "Princess of Wales Hospital"},
    {"pz_code": "PZ094", "region": "West Midlands", "name": "Princess Royal Hospital (Shrewsbury and Telford)"},
    {"pz_code": "PZ096", "region": "South West", "name": "Plymouth Children's Diabetes Service"},
    {"pz_code": "PZ097", "region": "West Midlands", "name": "City Hospital - Children's Diabetic Clinic"},
    {"pz_code": "PZ099", "region": "East of England", "name": "Lister Hospital"},
    {"pz_code": "PZ099", "region": "East of England", "name": "Queen Elizabeth II Hospital"},
    {"pz_code": "PZ100", "region": "South West", "name": "North Devon District Hospital"},
    {"pz_code": "PZ101", "region": "Yorkshire & Humber", "name": "Leeds Children's Hospital - Children's & Young People's Diabetes Centre"},
    {"pz_code": "PZ102", "region": "London & South East", "name": "Hillingdon Hospital - Children and Young People's Diabetes Team"},
    {"pz_code": "PZ104", "region": "North West", "name": "Royal Albert Edward Infirmary - Wigan"},
    {"pz_code": "PZ105", "region": "Yorkshire & Humber", "name": "St Luke's Hospital - Bradford Children's Diabetes Team"},
    {"pz_code": "PZ106", "region": "North West", "name": "Victoria Hospital (Blackpool)"},
    {"pz_code": "PZ107", "region": "North East & North Cumbria", "name": "Queen Elizabeth Hospital (Gateshead)"},
    {"pz_code": "PZ108", "region": "West Midlands", "name": "Birmingham Children's Hospital"},
    {"pz_code": "PZ109", "region": "South Central", "name": "Lymington Hospital Paediatric Diabetes clinic"},
    {"pz_code": "PZ109", "region": "South Central", "name": "Southampton Children's Hospital - Paediatric Diabetes Clinic"},
    {"pz_code": "PZ110", "region": "North West", "name": "Ormskirk General Hospital"},
    {"pz_code": "PZ111", "region": "West Midlands", "name": "Hereford County Hospital"},
    {"pz_code": "PZ112", "region": "Yorkshire & Humber", "name": "Scarborough Hospital"},
    {"pz_code": "PZ113", "region": "Wales", "name": "University Hospital of Wales"},
    {"pz_code": "PZ114", "region": "Yorkshire & Humber", "name": "Selby Hospital"},
    {"pz_code": "PZ114", "region": "Yorkshire & Humber", "name": "York Hospital"},
    {"pz_code": "PZ118", "region": "London & South East", "name": "University Hospital Lewisham"},
    {"pz_code": "PZ119", "region": "London & South East", "name": "Darent Valley Hospital"},
    {"pz_code": "PZ120", "region": "North East & North Cumbria", "name": "North Tyneside General Hospital"},
    {"pz_code": "PZ120", "region": "North East & North Cumbria", "name": "Wansbeck General Hospital"},
    {"pz_code": "PZ121", "region": "West Midlands", "name": "George Eliot Hospital - Paediatric Diabetes Clinic"},
    {"pz_code": "PZ122", "region": "West Midlands", "name": "Hospital of St Cross, Rugby"},
    {"pz_code": "PZ122", "region": "West Midlands", "name": "University Hospital Coventry"},
    {"pz_code": "PZ126", "region": "London & South East", "name": "Medway Maritime Hospital"},
    {"pz_code": "PZ127", "region": "East of England", "name": "James Paget Hospital - Paediatric Diabetes Clinic and Adolescent Clinic"},
    {"pz_code": "PZ128", "region": "East Midlands", "name": "Pilgrim Hospital"},
    {"pz_code": "PZ129", "region": "Yorkshire & Humber", "name": "Harrogate District Hospital"},
    {"pz_code": "PZ130", "region": "London & South East", "name": "Chelsea and Westminster Hospital"},
    {"pz_code": "PZ131", "region": "East of England", "name": "Peterborough City Hospital"},
    {"pz_code": "PZ131", "region": "East of England", "name": "Stamford and Rutland Hospital"},
    {"pz_code": "PZ132", "region": "Wales", "name": "Ysbyty Gwynedd Hospital - Children's Diabetes Clinic"},
    {"pz_code": "PZ135", "region": "London & South East", "name": "Royal Alexandra Hospital - Children's Diabetes Clinic"},
    {"pz_code": "PZ136", "region": "North West", "name": "Royal Manchester Children's Hospital - Paediatric Diabetes Unit"},
    {"pz_code": "PZ137", "region": "South West", "name": "Musgrove Park Hospital - Children's Diabetes Clinic"},
    {"pz_code": "PZ138", "region": "West Midlands", "name": "Warwick Hospital - Paediatric Diabetes Clinic"},
    {"pz_code": "PZ139", "region": "South West", "name": "Bristol Children's Hospital"},
    {"pz_code": "PZ139", "region": "South West", "name": "South Bristol Community Hospital"},
    {"pz_code": "PZ139", "region": "South West", "name": "Southmead Hospital"},
    {"pz_code": "PZ139", "region": "South West", "name": "Weston General Hospital"},
    {"pz_code": "PZ140", "region": "North West", "name": "Tameside General Hospital - Paediatric Diabetes Clinic"},
    {"pz_code": "PZ144", "region": "West Midlands", "name": "Good Hope Hospital Diabetes Clinic"},
    {"pz_code": "PZ145", "region": "Thames Valley", "name": "Milton Keynes Hospital"},
    {"pz_code": "PZ146", "region": "East of England", "name": "Southend University Hospital - Paediatric Diabetes Clinics"},
    {"pz_code": "PZ149", "region": "Yorkshire & Humber", "name": "Barnsley Hospital - Paediatric and Young Adults Diabetes Clinic"},
    {"pz_code": "PZ150", "region": "North East & North Cumbria", "name": "Cumberland Infirmary - Carlisle and Penrith"},
    {"pz_code": "PZ151", "region": "London & South East", "name": "Queen Elizabeth Hospital (Sidcup)"},
    {"pz_code": "PZ151", "region": "London & South East", "name": "Queen Elizabeth Hospital (Woolwich)"},
    {"pz_code": "PZ152", "region": "South West", "name": "Torbay Hospital - Children's Diabetes Team"},
    {"pz_code": "PZ153", "region": "North West", "name": "Whiston Hospital"},
    {"pz_code": "PZ156", "region": "East of England", "name": "King's Lynn & Wisbech, The Queen Elizabeth Hospital"},
    {"pz_code": "PZ157", "region": "London & South East", "name": "Royal Free Hospital - Paediatric Diabetes Clinics"},
    {"pz_code": "PZ159", "region": "South Central", "name": "Basingstoke and North Hampshire Hospital"},
    {"pz_code": "PZ160", "region": "North East & North Cumbria", "name": "Bishop Auckland Hospital"},
    {"pz_code": "PZ161", "region": "North East & North Cumbria", "name": "Darlington Memorial Hospital"},
    {"pz_code": "PZ162", "region": "North East & North Cumbria", "name": "University Hospital of North Durham (and satellites)"},
    {"pz_code": "PZ163", "region": "North East & North Cumbria", "name": "University Hospital of Hartlepool"},
    {"pz_code": "PZ163", "region": "North East & North Cumbria", "name": "University Hospital of North Tees"},
    {"pz_code": "PZ164", "region": "Yorkshire & Humber", "name": "Rotherham Hospital"},
    {"pz_code": "PZ167", "region": "North West", "name": "Furness General Hospital"},
    {"pz_code": "PZ167", "region": "North West", "name": "Royal Lancaster Infirmary"},
    {"pz_code": "PZ167", "region": "North West", "name": "Westmoreland General Hospital"},
    {"pz_code": "PZ168", "region": "East Midlands", "name": "Grantham District General Hospital - Kingfisher Children's Unit"},
    {"pz_code": "PZ169", "region": "South Central", "name": "Salisbury District Hospital - Diabetes Clinic"},
    {"pz_code": "PZ170", "region": "North West", "name": "Arrowe Park Hospital"},
    {"pz_code": "PZ171", "region": "East of England", "name": "Broomfield Hospital - Children's Diabetes Team"},
    {"pz_code": "PZ172", "region": "East of England", "name": "Hemel Hempstead Hospital"},
    {"pz_code": "PZ172", "region": "East of England", "name": "Watford General Hospital"},
    {"pz_code": "PZ173", "region": "South West", "name": "Yeovil District Hospital - Children's Diabetes Clinic"},
    {"pz_code": "PZ174", "region": "East Midlands", "name": "Kettering General Hospital"},
    {"pz_code": "PZ176", "region": "London & South East", "name": "St Peter's Hospital - Paediatric Diabetes Service"},
    {"pz_code": "PZ177", "region": "North West", "name": "Royal Bolton Hospital"},
    {"pz_code": "PZ178", "region": "West Midlands", "name": "Manor Hospital - Walsall Kids' Diabetes Team"},
    {"pz_code": "PZ179", "region": "North West", "name": "Countess of Chester Children and Young Persons Diabetes Clinic"},
    {"pz_code": "PZ180", "region": "East Midlands", "name": "Sherwood Forest Hospital NHS Foundation Trust"},
    {"pz_code": "PZ181", "region": "East of England", "name": "Ipswich Hospital"},
    {"pz_code": "PZ182", "region": "London & South East", "name": "West Middlesex Hospital"},
    {"pz_code": "PZ183", "region": "North West", "name": "Chorley District Hospital"},
    {"pz_code": "PZ183", "region": "North West", "name": "Royal Preston Hospital"},
    {"pz_code": "PZ186", "region": "Yorkshire & Humber", "name": "Calderdale and Huddersfield Foundation NHS Trust"},
    {"pz_code": "PZ187", "region": "Wales", "name": "Wrexham Maelor Hospital- Paediatric Diabetes Unit"},
    {"pz_code": "PZ189", "region": "Wales", "name": "Royal Glamorgan Hospital"},
    {"pz_code": "PZ191", "region": "London & South East", "name": "Ealing Hospital"},
    {"pz_code": "PZ193", "region": "Wales", "name": "Neath Port Talbot Hospital"},
    {"pz_code": "PZ196", "region": "London & South East", "name": "Great Ormond Street Hospital - Children and Young Peoples Diabetes Service"},
    {"pz_code": "PZ199", "region": "London & South East", "name": "North Middlesex University Hospital - Paediatric Diabetes Clinic"},
    {"pz_code": "PZ200", "region": "East of England", "name": "Princess Alexandra Hospital"},
    {"pz_code": "PZ202", "region": "London & South East", "name": "Hammersmith Hospital"},
    {"pz_code": "PZ202", "region": "London & South East", "name": "St Mary's Hospital, Imperial College"},
    {"pz_code": "PZ203", "region": "London & South East", "name": "University College London Hospital"},
    {"pz_code": "PZ213", "region": "London & South East", "name": "Crawley Hospital"},
    {"pz_code": "PZ213", "region": "London & South East", "name": "East Surrey Hospital"},
    {"pz_code": "PZ213", "region": "London & South East", "name": "Horsham Hospital"},
    {"pz_code": "PZ215", "region": "London & South East", "name": "King's College Hospital - Diabetes Clinic"},
    {"pz_code": "PZ218", "region": "London & South East", "name": "Frimley Park Hospital - Diabetes Clinic"},
    {"pz_code": "PZ219", "region": "Yorkshire & Humber", "name": "Sheffield Children's Hospital"},
    {"pz_code": "PZ220", "region": "East of England", "name": "Bedford Hospital - Children's Diabetes Clinic"},
    {"pz_code": "PZ221", "region": "South West", "name": "Great Western Hospital - Swindon Children's Diabetes Clinic"},
    {"pz_code": "PZ222", "region": "West Midlands", "name": "New Cross Hospital"},
    {"pz_code": "PZ223", "region": "West Midlands", "name": "Sandwell Hospital - Children's Diabetes Clinic"},
    {"pz_code": "PZ225", "region": "West Midlands", "name": "Worcester Royal Hospital"},
    {"pz_code": "PZ226", "region": "Yorkshire & Humber", "name": "Dewsbury and District Hospital"},
    {"pz_code": "PZ228", "region": "Wales", "name": "Prince Charles Hospital - Children Diabetes Clinic"},
    {"pz_code": "PZ230", "region": "London & South East", "name": "Conquest Hospital"},
    {"pz_code": "PZ230", "region": "London & South East", "name": "Eastbourne District General Hospital"},
    {"pz_code": "PZ231", "region": "North West", "name": "Salford Royal Hospital - Paediatric Diabetes Team"},
    {"pz_code": "PZ232", "region": "London & South East", "name": "King George Hospital (Goodmayes)"},
    {"pz_code": "PZ232", "region": "London & South East", "name": "Queen's Hospital (Romford)"},
    {"pz_code": "PZ238", "region": "South Central", "name": "Queen Alexandra Hospital - Portsmouth Paediatric Diabetes Team"},
    {"pz_code": "PZ240", "region": "West Midlands", "name": "Russells Hall Hospital"},
    {"pz_code": "PZ242", "region": "South West", "name": "Gloucester Royal and Cheltenham General Hospital"},
    {"pz_code": "PZ244", "region": "Wales", "name": "Bronglais General Hospital"},
    {"pz_code": "PZ244", "region": "Wales", "name": "Glangwili General Hospital"},
    {"pz_code": "PZ244", "region": "Wales", "name": "Withybush General Hospital"},
    {"pz_code": "PZ245", "region": "Wales", "name": "Chepstow Community Hospital"},
    {"pz_code": "PZ245", "region": "Wales", "name": "Nevil Hall Hospital"},
    {"pz_code": "PZ245", "region": "Wales", "name": "Serennu Children's Centre"},
    {"pz_code": "PZ245", "region": "Wales", "name": "St Woolos Hospital"},
    {"pz_code": "PZ245", "region": "Wales", "name": "Ysbyty Aneurin Bevan"},
    {"pz_code": "PZ245", "region": "Wales", "name": "Ysbyty Ystrad Fawr"},
    {"pz_code": "PZ246", "region": "North West", "name": "Rochdale Infirmary"},
    {"pz_code": "PZ246", "region": "North West", "name": "Royal Oldham Hospital"},
    {"pz_code": "PZ247", "region": "North West", "name": "North Manchester General Hospital"},
    {"pz_code": "PZ248", "region": "Jersey", "name": "Jersey Diabetes Service"},
    {"pz_code": "PZ249", "region": "North East & North Cumbria", "name": "Friarage Hospital - Paediatric Diabetes Unit"},
    {"pz_code": "PZ249", "region": "North East & North Cumbria", "name": "James Cook University Hospital"},
    {"pz_code": "PZ250", "region": "North East & North Cumbria", "name": "South Tyneside District Hospital - Children and Young People's Diabetes Service"},
    {"pz_code": "PZ250", "region": "North East & North Cumbria", "name": "Sunderland Royal Hospital - Children and Young People's Diabetes Service"},
    {"pz_code": "PZ251", "region": "Yorkshire & Humber", "name": "Pinderfields General Hospital"},
    {"pz_code": "PZ252", "region": "Yorkshire & Humber", "name": "Pontefract General Hospital"},
    {"pz_code": "PZ253", "region": "London & South East", "name": "Maidstone Hospital Diabetes Clinic"},
    {"pz_code": "PZ253", "region": "London & South East", "name": "Tunbridge Wells Diabetes Clinic"},
    {"pz_code": "PZ256", "region": "Isle of Man", "name": "Noble's Hospital"},
]

REGION_SLUG_MAP = {
    "East Midlands": "east-midlands",
    "East of England": "east-of-england",
    "Jersey": "jersey",
    "London & South East": "london-south-east",
    "North East & North Cumbria": "north-east-north-cumbria",
    "North West": "north-west",
    "South Central": "south-central",
    "South West": "south-west",
    "Thames Valley": "thames-valley",
    "Wales": "wales",
    "West Midlands": "west-midlands",
    "Yorkshire & Humber": "yorkshire-humber",
    "Isle of Man": "isle-of-man",
}

SLUG_REGION_MAP = {v: k for k, v in REGION_SLUG_MAP.items()}


def get_clinics_for_region(region_slug):
    """Return clinics for a region slug, sorted alphabetically by name."""
    region_name = SLUG_REGION_MAP.get(region_slug)
    if not region_name:
        return []
    return sorted(
        [c for c in CLINICS if c["region"] == region_name],
        key=lambda c: c["name"].lower(),
    )


def get_all_clinics_sorted():
    """Return all clinics sorted alphabetically by name."""
    return sorted(CLINICS, key=lambda c: c["name"].lower())


def get_current_clinic_display_name(pz_code):
    if pz_code is None:
        return None
    
    for clinic in CLINICS:
        if clinic["pz_code"] == pz_code:
            return f"{clinic['name']} - {clinic['region']}"


def get_all_clinic_display_names():
    clinics = get_all_clinics_sorted()

    return [f"{clinic['name']} - {clinic['region']}" for clinic in clinics]


def get_pz_code_by_display_name(display_name):
    for clinic in CLINICS:
        if f"{clinic['name']} - {clinic['region']}" == display_name:
            return clinic["pz_code"]
