# Generated by Django 5.2.10 on 2026-01-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.JSONField(blank=True, default=list)),
                ('rating', models.CharField(blank=True, choices=[('very-good', 'Very good'), ('good', 'Good'), ('neither', 'Neither good nor poor'), ('poor', 'Poor'), ('very-poor', 'Very poor')], default='', max_length=20)),
                ('hospital', models.CharField(blank=True, choices=[('hospital-1', 'Hospital 1'), ('hospital-2', 'Hospital 2'), ('hospital-3', 'Hospital 3')], default='', max_length=20)),
                ('child_age', models.CharField(blank=True, default='', max_length=10)),
                ('comments', models.TextField(blank=True, default='')),
            ],
        ),
    ]
