# Generated by Django 5.2.10 on 2026-02-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cyp', 'A child or young person with diabetes'), ('parent', 'The parent/carer of a child or young person with diabetes')], max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('q1_region', models.CharField(blank=True, choices=[('north-east-north-cumbria', 'North East & North Cumbria'), ('north-west', 'North West'), ('yorkshire-humber', 'Yorkshire & Humber'), ('east-midlands', 'East Midlands'), ('west-midlands', 'West Midlands'), ('east-of-england', 'East of England'), ('south-central', 'South Central'), ('london-south-east', 'London & South East'), ('south-west', 'South West'), ('thames-valley', 'Thames Valley'), ('wales', 'Wales'), ('jersey', 'Jersey')], default='', max_length=30)),
                ('q2_hospital', models.CharField(blank=True, default='', max_length=200)),
                ('q4_gender', models.CharField(blank=True, choices=[('boy', 'Boy'), ('girl', 'Girl'), ('other', 'A gender not listed here'), ('prefer-not-to-say', 'Prefer not to say')], default='', max_length=20)),
                ('q5_relationship', models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('grandmother', 'Grandmother'), ('grandfather', 'Grandfather'), ('other', 'Other guardian or family member')], default='', max_length=20)),
                ('q6_diabetes_type', models.CharField(blank=True, choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('other', 'Other')], default='', max_length=10)),
                ('q7_age_at_diagnosis', models.CharField(blank=True, choices=[('0-3', '3 years or younger'), ('4-7', '4 – 7 years'), ('8-11', '8 – 11 years'), ('12-16', '12 – 16 years'), ('17-19', '17 – 19 years')], default='', max_length=10)),
                ('q8_ethnicity', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('asian', 'Asian'), ('mixed', 'Mixed'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], default='', max_length=20)),
                ('q9_education_stage', models.CharField(blank=True, choices=[('nursery', 'Nursery'), ('reception', 'Reception'), ('ks1', 'Key stage 1 (Years 1 & 2)'), ('ks2', 'Key stage 2 (Years 3 to 6)'), ('ks3', 'Key stage 3 (Years 7 to 9)'), ('ks4', 'Key stage 4 (Years 10 & 11)'), ('ks5', 'Key stage 5 (Years 12 & 13)'), ('other', 'Other')], default='', max_length=20)),
                ('q9_education_stage_other', models.CharField(blank=True, default='', max_length=200)),
                ('q10_school_type', models.CharField(blank=True, choices=[('state', 'State funded school'), ('private', 'Private school'), ('home', 'Home schooled/educated')], default='', max_length=10)),
                ('q11_home_education_reason', models.CharField(blank=True, choices=[('no', 'No, it was for other reasons'), ('partly', 'Partly, the diabetes diagnosis influenced my decision'), ('yes', 'Yes, it was mainly because of the diabetes diagnosis'), ('prefer-not-to-say', 'Prefer not to say')], default='', max_length=20)),
                ('q12_free_school_meals', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont-know', "I don't know"), ('prefer-not-to-say', 'Prefer not to say')], default='', max_length=20)),
                ('q13_healthcare_plan', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont-know', "I don't know")], default='', max_length=10)),
                ('q14_plan_coverage', models.CharField(blank=True, choices=[('yes', 'Yes'), ('partially', 'Partially covers diabetes needs at school'), ('no', 'No'), ('dont-know', "I don't know")], default='', max_length=12)),
                ('q15_school_contact', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont-know', "I don't know")], default='', max_length=10)),
                ('q16_insulin_or_monitor', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=5)),
                ('q17_insulin_method', models.JSONField(blank=True, default=list)),
                ('q18_glucose_monitoring', models.JSONField(blank=True, default=list)),
                ('q19_remote_monitoring', models.CharField(blank=True, choices=[('yes-always', 'Yes, always'), ('yes-sometimes', 'Yes, sometimes'), ('no-never', 'No, never'), ('dont-know', "I don't know")], default='', max_length=15)),
                ('q20_contact_school', models.CharField(blank=True, choices=[('yes-always', 'Yes, always'), ('yes-sometimes', 'Yes, sometimes'), ('no-never', 'No, never'), ('dont-know', "I don't know"), ('not-applicable', 'Not applicable')], default='', max_length=15)),
                ('q21_smartphone_use', models.CharField(blank=True, choices=[('yes-always', 'Yes, always'), ('yes-sometimes', 'Yes, sometimes'), ('no-never', 'No, never'), ('not-applicable', 'Not applicable')], default='', max_length=15)),
                ('q22_private_room', models.CharField(blank=True, choices=[('yes-always', 'Yes, always'), ('yes-sometimes', 'Yes, sometimes'), ('no-never', 'No, never'), ('dont-know', "I don't know"), ('not-applicable', 'Not applicable')], default='', max_length=15)),
                ('q23_classroom_management', models.CharField(blank=True, choices=[('yes-always', 'Yes, always'), ('yes-sometimes', 'Yes, sometimes'), ('no-never', 'No, never'), ('dont-know', "I don't know"), ('not-applicable', 'Not applicable')], default='', max_length=15)),
                ('q24_trained_staff', models.CharField(blank=True, choices=[('yes-always', 'Yes, always'), ('yes-sometimes', 'Yes, sometimes'), ('no-never', 'No, never'), ('dont-know', "I don't know")], default='', max_length=15)),
                ('q25_carb_counting', models.CharField(blank=True, choices=[('yes-always', 'Yes, always'), ('yes-sometimes', 'Yes, sometimes'), ('no-never', 'No, never'), ('dont-know', "I don't know"), ('not-applicable', 'Not applicable')], default='', max_length=15)),
                ('q26_missed_lessons', models.CharField(blank=True, default='', max_length=10)),
                ('q27_absences_authorised', models.CharField(blank=True, choices=[('yes-always', 'Yes, always'), ('yes-sometimes', 'Yes, sometimes'), ('no-never', 'No, never'), ('dont-know', "I don't know")], default='', max_length=15)),
                ('q28_attendance_impacted', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont-know', "I don't know")], default='', max_length=10)),
                ('q29_days_off', models.CharField(blank=True, default='', max_length=10)),
                ('q30_moved_schools', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=5)),
                ('q31_excluded_activities', models.JSONField(blank=True, default=list)),
                ('q31_excluded_activities_other', models.CharField(blank=True, default='', max_length=200)),
                ('q32_performance_impact', models.CharField(blank=True, choices=[('never', 'Never'), ('rarely', 'Rarely'), ('sometimes', 'Sometimes'), ('often', 'Often'), ('always', 'Always'), ('dont-know', "I don't know")], default='', max_length=15)),
                ('q33_teacher_understanding', models.CharField(blank=True, choices=[('yes-always', 'Yes, always'), ('yes-sometimes', 'Yes, sometimes'), ('no-never', 'No, never'), ('dont-know', "I don't know"), ('not-applicable', 'Not applicable')], default='', max_length=15)),
                ('q34_reasonable_adjustments', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not-applicable', 'Not applicable')], default='', max_length=15)),
                ('q35_felt_left_out', models.CharField(blank=True, choices=[('never', 'Never'), ('rarely', 'Rarely'), ('sometimes', 'Sometimes'), ('often', 'Often'), ('always', 'Always'), ('dont-know', "I don't know")], default='', max_length=15)),
                ('q36_lost_income', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not-applicable', 'Not applicable')], default='', max_length=15)),
                ('q37_anxiety_frequency', models.CharField(blank=True, choices=[('never', 'Never'), ('less-than-weekly', 'Less than once a week'), ('once-or-twice', 'Once or twice a week'), ('three-or-four', 'Three or four times a week'), ('every-day', 'Every day of the week')], default='', max_length=20)),
                ('q38_school_support', models.CharField(blank=True, choices=[('very-well', 'Very well supported'), ('well', 'Well supported'), ('neutral', 'Neutral'), ('poorly', 'Poorly supported'), ('very-poorly', 'Very poorly supported'), ('not-applicable', 'Not applicable')], default='', max_length=15)),
                ('q39_team_support', models.CharField(blank=True, choices=[('very-well', 'Very well supported'), ('well', 'Well supported'), ('neutral', 'Neutral'), ('poorly', 'Poorly supported'), ('very-poorly', 'Very poorly supported')], default='', max_length=15)),
                ('q40_worked_well', models.TextField(blank=True, default='')),
                ('q41_not_worked_well', models.TextField(blank=True, default='')),
                ('q42_improvements', models.TextField(blank=True, default='')),
            ],
        ),
    ]
