# Generated by Django 6.0.2 on 2026-02-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='q4_gender',
            field=models.CharField(blank=True, choices=[('boy', 'q4.boy'), ('girl', 'q4.girl'), ('other', 'q4.other'), ('prefer-not-to-say', 'q4.prefer-not-to-say')], default='', max_length=20),
        ),
    ]
