#!/bin/bash -e

uv sync
uv run django-admin makemessages --all
uv run manage.py collectstatic --noinput
uv run manage.py makemigrations
uv run manage.py migrate
uv run django-admin compilemessages
uv run manage.py seed
uv run manage.py runserver 0.0.0.0:8000